# Generated by Django 4.1.3 on 2022-11-30 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country_id',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='tourguide',
            name='user_id',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='tour.country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='sight',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sights', to='tour.city', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_guide', to=settings.AUTH_USER_MODEL, verbose_name='user_id'),
        ),
        migrations.AlterField(
            model_name='city',
            name='history',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='history'),
        ),
        migrations.AlterField(
            model_name='country',
            name='main_info',
            field=models.TextField(blank=True, null=True, verbose_name='main_info'),
        ),
    ]
