# Generated by Django 4.1.3 on 2022-11-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_remove_city_country_id_remove_sight_city_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routesight',
            old_name='route_id',
            new_name='route',
        ),
        migrations.RenameField(
            model_name='routesight',
            old_name='sight_id',
            new_name='sight',
        ),
    ]
