# Generated by Django 4.1.3 on 2022-12-09 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tour', '0006_sightreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sightreview',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='sightreview',
            name='reader',
        ),
        migrations.AddField(
            model_name='sightreview',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sight_reviews', to=settings.AUTH_USER_MODEL, verbose_name='reviewer'),
            preserve_default=False,
        ),
    ]
